app/src/main/res/layout/fragment_best.xml
app/src/main/res/layout/fragment_main.xml
app/src/main/res/layout/fragment_side.xml
app/src/main/res/layout/fragment_soup.xml
app/src/main/res/values/strings.xml

- close #9 
- fragment tag를 string value로 추출 후 관리

ui: fragment tag를 추출 후 관리

---

app/src/main/java/com/woowa/banchan/data/remote/dto/BestFood.kt
app/src/main/java/com/woowa/banchan/data/remote/dto/BestFoodCategory.kt
app/src/main/java/com/woowa/banchan/data/remote/dto/DetailItem.kt
app/src/main/java/com/woowa/banchan/data/remote/dto/Food.kt
app/src/main/java/com/woowa/banchan/data/remote/dto/FoodDetail.kt
app/src/main/java/com/woowa/banchan/data/remote/dto/FoodItem.kt

feat: remote dto 생성

---

app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/DeleteCartUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/InsertCartUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartCheckStateUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartCountUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/interface/GetDetailFoodUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/interface/GetTotalFoodUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/DeleteFoodFromCartUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetDetailFoodUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/InsertFoodToCartUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/UpdateFoodCountUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderDetailUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetTotalOrderUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/InsertCartToOrderUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/GetOrderDetailUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/GetTotalOrderUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/InsertCartToOrderUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/inter/GetRecentlyViewedFoodsUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/interface/GetRecentlyViewedFoodsUseCase.kt

- close #30 
- cart를 호출하는 api를 추가함
- 기존에 맞지 않는 패키지 위치를 수정함
- 실제 사용되는 api를 위해 Network 관련 api를 수정함

refactor: local api 추가 및 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
app/src/main/res/layout/fragment_recent.xml
app/src/main/res/layout/item_recent.xml

- #14 
- #38 
- grid view를 통해 data를 2개씩 정렬해 보여준다.
- recently View recycler view btn callback 기능 구현
- 앞에서 만든 recent item을 재활용할 것인가?
- 똑같은 view에 대해서 하나의 파일을 더 만드는 것은 적합하지 않다고 판단
- 이를 재활용 하기로 결정함

ui: Recently viewed products 화면 구성

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartFooterBtnViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CheckHeaderViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentPreviewViewHolder.kt
app/src/main/res/layout/item_cart.xml
app/src/main/res/layout/item_recent_preview.xml

- #36 
- cart view의 callback 기능 구현
- 전체를 listener interface를 만들어서 콜백을 받을지에 대한 고민
- 함수의 변수식을 이용해 일부 구현하고 Fragment에서는 listener를 제공해 각 기능에 대한 행동을 수행하게 함

feat: cart recycler view btn callback 기능 구현

---

app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/viewholder/SoupSideHeaderViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/adapter/SoupSideRVAdapter.kt
app/src/main/res/layout/fragment_side.xml
app/src/main/res/layout/item_rv_detail.xml
app/src/main/res/values/strings.xml

- close #40 
- api 호출하여 side 데이터 받아오기
- 화면 완성
- 어댑터 패키지 분리 (우선은 임의로 soupside라는 패키지를 만들었으니 참고해주시길 바랍니다!)
- 주호님과 회의를 통해 추후 다른 방법이 없을지 생각해보기로 하였습니다.

feat: Side 화면 구현

---

app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/InsertCartUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/InsertCartUseCase.kt
app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/event/SingleEvent.kt
app/src/main/java/com/woowa/banchan/ui/common/livedata/SingleLiveData.kt
app/src/main/java/com/woowa/banchan/ui/common/popup/CartCompleteFragment.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
app/src/main/res/drawable/background_dialog.xml
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/fragment_cart_complete.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

- close #43 
- 수량 기능 구현
- cart에 담기 기능 구현
- Dialog 백스택 관리
- DetailActivity에서 dialog를 통해 CartActivity에 진입했다가 다시 DetailActivity에 진입했을 시 dialog가 남아있음

feat: Detail 화면 기능 구현

---

app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt

- #58 
- UserIcon을 눌렀을 때 OrderActivity로 이동하는 메소드를 추가
- launchIn을 통해 데이터 로드를 관찰하고 뷰를 갱신함

fix: Order 화면 데이터 표시 버그 해결

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/res/layout/item_cart.xml

- close #68 
- 사용자가 직접 입력할 수 있도록 edittextview로 변경함
- 변경된 데이터들은 최소수량 1, 최대수량 100으로 설정하여
- 이를 벗어날 경우 조정된 값으로 저장된다.

feat: Cart 수량 변경을 키보드 입력받을 수 있도록 구현

---

app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailHeaderViewHolder.kt

- close #75 
- 기존 0 -> 20으로 늘어나는 표기를 20 -> 0으로 변경

fix: 배송 남은 시간 버그 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt

- close #84 
- 데이터 로드 시 Job을 반환해 다른 곳에서 이를 관리하는 것은 적합하지 않다고 판단
- 이를 Unit으로 변경한다.

refactor: 데이터 로드하는 함수의 job 반환형을 Unit으로 변환

---

app/src/main/java/com/woowa/banchan/ui/common/viewutils/LoadingUtil.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/fragment_best.xml
app/src/main/res/layout/fragment_main.xml
app/src/main/res/layout/fragment_side.xml
app/src/main/res/layout/fragment_soup.xml

- close #104 
- loading ui 추가
- progress bar를 활용한 loading ui 추가
- loading 기능 추가
- UiState가 Loading일 때, Loading을 보여준다.
- 로딩상태가 아닐 경우 Loading을 숨기며 본 내용을 보여준다.

feat: loading 추가

---

app/src/main/java/com/woowa/banchan/ui/common/custom/CustomErrorView.kt
app/src/main/java/com/woowa/banchan/ui/common/viewutils/LoadingUtil.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/fragment_best.xml
app/src/main/res/layout/fragment_main.xml
app/src/main/res/layout/fragment_side.xml
app/src/main/res/layout/fragment_soup.xml
app/src/main/res/layout/view_error_custom.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml

- close #105
- Error CustomView 구현
- 네트워크 처리 오류에 대한 뷰를 표시

Feat: error 로직 처리

---

app/src/main/java/com/woowa/banchan/ui/common/custom/CustomErrorView.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupViewModel.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/fragment_best.xml
app/src/main/res/layout/fragment_main.xml
app/src/main/res/layout/fragment_side.xml
app/src/main/res/layout/fragment_soup.xml

- close #112 
- home 화면 에러 버튼 기능 구현
- Food detail 화면 에러 버튼 기능 구현

Feat: 에러 버튼 기능 추가

---

app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/GetRecentlyViewedFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentGridItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
app/src/main/res/layout/fragment_recent.xml
app/src/main/res/layout/item_recent_grid.xml

- close #98 
- Cart의 변화상태에 따라 Recent도 변하도록 Flow 구현
- 클릭이벤트 ViewModel로 이전

feat: Cart와 Recent Flow로 연결

---

app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt

- close #122 
- DB를 Main Thread 위에서 동작하게 되어 일어나는 버그를 수정

fix: DB 버그 수정

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt

- close #116 
- detail -> cart -> detail 또는 cart -> detail -> cart 움직일 때 똑같은 Activity가 생성되는 것을 해결
- 각각 singleTask로 실행해 더이상의 중복되는 activity를 막음

refactor: activity 스택관리

---

app/src/main/java/com/woowa/banchan/ui/common/custom/CustomToolbar.kt
app/src/main/java/com/woowa/banchan/ui/common/viewutils/ImageViewUtil.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
app/src/main/res/drawable/placeholder.xml
app/src/main/res/layout/view_tool_bar_custom.xml
app/src/main/res/values/styles.xml

- close #132 
- 크기가 작아서 보여지지 않는 버그를 수정

refactor: 아이콘 배지 크기 변경

---

app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt

fix: recently viewed 상단 제목 변경

---

app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt

- close #138 
- ViewModel이 binding 되어 있지 않아, 새로고침이 안 되던 버그 수정

fix: ViewModel DataBinding 추가

---

app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt

- close #142 
- 1 ~ 100까지만 개수를 변경할 수 있도록 수정

fix: FoodItem Count 범위 수정

---

app/src/main/java/com/woowa/banchan/data/local/dao/RecentDao.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/GetRecentlyViewedFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/custom/CustomToolbar.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
app/src/main/java/com/woowa/banchan/utils/DateUtil.kt

- close #145 
- 최근 조회목록에서 다시 한번 상세정보를 들어갔다 나올 시, 시간이 갱신되도록 Flow로 수정

refactor: 최근 조회 목록 갱신

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt

- close #144 
- visibility 수정
저희가 예상했던 거랑 다르게 visibility만 수정해주니까 해결이 되었는데
혹시 제 손이 느려서 그런 것일 수도 있으니
지금 이 PR버전에서도 똑같은 버그가 일어나는지 주호님께서 다시 확인 해주실 수 있나요?!

fix: cart에 빈 상품이 담기던 버그 수정

---

app/src/main/java/com/woowa/banchan/domain/model/FoodItem.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddViewModel.kt
app/src/main/java/com/woowa/banchan/ui/common/key/Key.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt

- close #147 
- BottomSheet 회전 시 앱이 죽던 버그 수정
어떤 것이 오류인지 잘 몰라서 많이 찾아보다가
생성자와 관련한 오류 같길래
Bundle로 인자 값을 넘기는 방식으로 수정하였더니 해결됐습니다.
(한번 계속 찾아봐야 할 것 같습니다.)

fix: BottomSheet 화면 회전시 생기던 버그 수정

---

app/build.gradle
app/src/main/java/com/woowa/banchan/data/local/dao/RecentDao.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/domain/model/FoodItem.kt
app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/GetRecentlyViewedFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddViewModel.kt
app/src/main/java/com/woowa/banchan/ui/common/custom/CustomToolbar.kt
app/src/main/java/com/woowa/banchan/ui/common/key/Key.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
app/src/main/java/com/woowa/banchan/utils/DateUtil.kt

- 24시간이 지났을 때 최근 목록이 지워져야 하지만 MainThread에서 동작 돼서 앱이 죽어버림 이 버그를 수정

version update 1.0.2 -> 1.0.3
