app/src/main/AndroidManifest.xml
app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
app/src/main/res/drawable/background_splash_screen.xml
app/src/main/res/values-night-v31/themes.xml
app/src/main/res/values-v31/themes.xml
app/src/main/res/values/themes.xml

- close #15 
- splash 화면 구현
- themes-31v를 통해 android 12 이후 버전도 대응
- 기존 themes.xml를 통해 android 11 이전 버전도 대응
- 어떻게 android 12와 그 이전버전을 대응할 수 있을까?
- 다음의 내용을 참고해 개발했다. -> [링크](https://medium.com/@radomir9720/android-splash-screen-easy-setup-for-both-11-version-and-lower-and-12-287ccb86f9c7)

ui: splash 화면 구성

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/remote/dto/FoodItem.kt
app/src/main/java/com/woowa/banchan/data/remote/repository/FoodRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/domain/UiState.kt
app/src/main/java/com/woowa/banchan/domain/repository/FoodRepository.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/GetFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetBestFoodsUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetFoodsUseCase.kt
app/src/main/java/com/woowa/banchan/ui/common/uistate/UiState.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeItemAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestBindingAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
app/src/main/java/com/woowa/banchan/utils/Toast.kt
app/src/main/res/layout/fragment_best.xml
app/src/main/res/layout/item_best_header.xml
app/src/main/res/layout/item_best_recyclerview.xml
app/src/main/res/layout/item_home.xml
build.gradle

- close #25 
- Banchan Api를 통해 BestFood 데이터를 받아온다.
- 이미지를 띄워주기 위해 Glide를 build gradle에 추가한다.
- 데이터를 RecyclerView에 띄워준다.
RecyclerView.Adapter -> ListAdapter로 마이그레이션 하였습니다.
`ListAdapter`의 `submitList`는 비동기적으로 처리되기 때문에
앱에 처음 진입시 스크롤이 맨 위가 아닌 중간으로 가 있는 버그가 생겼습니다.
저는 처음에 아래와 같이 정의하였습니다.
``` kotlin
override fun getItemCount(): Int {
return currentList.size * 2 + 1
}
```
그 이유는 아래와 같습니다.
- FoodCategory 하나당 2개의 아이템이 필요 (2,3번) -> size * 2
- 최상단 헤더는 고정 (1번) -> size +1
하지만 1번 헤더는 data를 받아와서 처리하는 방식이 아니기 때문에 바로 로드가 되었고,
나머지 2,3번 아이템은 비동기적으로 처리되기 때문에 나중에 로드 되었습니다.
그러다보니 앱을 처음 실행했을 때
아래와 같이 헤더가 아니라 아이템이 먼저 보이는 현상이 발생하였습니다.
(스크롤해서 위로 올리면 헤더는 정상적으로 나타나 있습니다.)
``` kotlin
fun submitHeaderList(list: List<BestFoodCategory>) {
val newList = mutableListOf<BestFoodCategory?>()
newList.add(null) //1번 헤더
for …
```

feat: Best 화면 기능 구현

---

app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/GetFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetBestFoodsUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetFoodsUseCase.kt
app/src/main/java/com/woowa/banchan/ui/common/uistate/UiState.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt

- close #28
- uiState를 제네릭 타입으로 변환한다.
- 이는 다음의 이유를 가짐
- view에서 데이터를 타입캐스팅 과정에서 실패할 수 있다.
- 이는 ui layer에서 하는 작업이 아니라고 판단
- 따라서, 제네릭 타입으로 변환해 flow 상에서 타입을 그대로 전달 받기를 수행함

refactor: uiState 제네릭 변환

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/woowa/banchan/data/local/dao/OrderItemDao.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/entity/OrderItemDto.kt
app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/di/DataBaseModule.kt
app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
app/src/main/java/com/woowa/banchan/domain/model/OrderItem.kt
app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderDetailUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderDetailUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetTotalOrderUseCase.kt
app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailRVTag.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/OrderDetailRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailHeaderViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailViewHolder.kt
app/src/main/res/layout/activity_order_detail.xml
app/src/main/res/layout/item_order_detail.xml
app/src/main/res/layout/item_order_detail_header.xml
app/src/main/res/values/strings.xml

- close #50 
- Order Detail 화면 구현하기
- Order Detail layout 구현
- RecyclerView Adapter 구현 및 부착
- ToolBar 기능 구현 및 타이틀 설정
- 받아온 orderId가 없을 경우 해당 화면은 즉시 종료한다.
- Order Detail 화면 Data Load
- Database에서 Order Detail Data Load
- datasource 및 repository, usecase 의존성 주입

feat: order detail 화면 구현하기

---

app/src/main/java/com/woowa/banchan/data/local/entity/CartDto.kt
app/src/main/java/com/woowa/banchan/data/local/entity/OrderItemDto.kt

- close #61 
- 에러 원인
- orderItem id를 -1로 지정해서 삽입함
- 리스트로 전달할 때 모두 -1로 지정되다보니 primaryKey가 중복되어 삽입이 안됨
- autuGenerate가 되도록 삽입 시 id를 null로 넣어주면서 해결했다.

fix: Cart to OrderItem 삽입 시 에러 해결

---

app/src/main/java/com/woowa/banchan/data/local/dao/RecentDao.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/entity/RecentDto.kt
app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
app/src/main/java/com/woowa/banchan/domain/model/Recent.kt
app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/InsertRecentlyViewedFoodsUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/recent/inter/InsertRecentlyViewedFoodsUseCase.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentPreviewViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
app/src/main/java/com/woowa/banchan/utils/DateUtil.kt

- close #66 
- 상품 Recently Viewed Products 기능 구현
- 상품 조회 시 최근 본 상품 테이블 항목에 추가 기능 구현
- 만일 기존에 데이터가 있다면 새로운 시간대로 갱신한다.
- Recently Viewed Products 정렬
- Cart View에서 최대 7개 항목만 시간순으로 보여준다.
- 전체 불러올 때 시간순서대로 불러온다.
- Recently Viewed Products 시간 오류 해결
- 최근 본 시간이 -초가 되는 것을 확인
- 이는 앱이 실행할 때 DateUtil에서 초기화된 시간을 기준으로 확인하기 때문에 그 이후에 보는 아이템들에 대해서 미래에 확인한 것으로 판단이 됨
- 이를 getUpdateDate를 얻을 때마다 기기 시간을 얻어와 갱신하여 해결함

feat: Recently Viewed Products 아이템 추가 기능 구현 및 버그 수정

---

app/src/main/java/com/woowa/banchan/data/local/entity/RecentDto.kt
app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
app/src/main/java/com/woowa/banchan/domain/model/Recent.kt

- close #71 
- api에서 받아오는 데이터의 nPrice는 nullable하다.
- 하지만 여기에선 non-null이기에 api에 맞추어 nullable로 처리한다.
- recently view에서 nPrice가 null이면 원본가격 텍스트를 보여주지 않는다.

refactor: Recent Table nPrice nullable 처리

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CheckHeaderViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/common/popup/CartCompleteFragment.kt
app/src/main/res/layout/item_cart_check_header.xml

- close #80 
- 카트 아이템 수량 변경에 따라 우측 하단 가격 변경
- 카트 화면에서 장바구니 버튼을 추가할 시 중복 activity를 생성하는 것을 해결
- 전체 선택 기능 구현
- 전체 리스트에 대한 flag로 현재 선택된 아이템들에 대한 내용을 기록한다.
- index -> 1 일경우 1번째자리에 bit를 토글해서 기록
- 이를 viewholder에서 확인 후 변경한다.
- 전체 선택을 위해 모든 아이템의 checkState를 확인할 것인가
- 아이템 전체가 체크가 되어 있지 않을 때 전체 선택을 보여줘야 한다.
- 이를 아이템이 변경될 때마다 확인하는 것은 매우 비효율 적이다.
- 따라서, 하나의 비트연산할 변수를 두고 각 아이템의 비트연산을 통해 모두 checkState가 0인지를 확인한다.
- 받아올 때 리스트의 인덱스와 checkState를 통해 1 or 0을 flag 세우고 bind를 호출해 이를 갱신한다.

feat: Cart 버그 수정 및 전체 선택 기능 구현

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/entity/RecentDto.kt
app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/domain/model/Recent.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/RecentPreviewRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentPreviewViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
app/src/main/res/layout/item_recent.xml

- close #76 
- 클릭 리스너를 추가해서 Detail 화면으로 이동한다.
- 최근 본 상품 클릭 시 Detail 화면 이동
-  최근 본 상품 테이블 갱신 시점 구현
- 데이터들을 불러올 때 24시간 전인 데이터들은 그 순간 delete 요청을 수행해 갱신한다.
- 장바구니 아이콘 표시 적용
- 최근 본 상품에서 장바구니에 있는 아이템에 대해 체크 표시
- 체크 클릭 시 삭제 기능 구현
- +추가
- DataSource와 Repository의 역할 재정의
- DataSource는 데이터를 가져오고 전달하는 역할의 객체로 둔다.
- Repository에서 필요로되는 데이터를 파싱하고 적절한 데이터를 전달한다.
- 이 역할을 다시 정의하며 코드를 수정한다.
- 할인율 음수값이 나오는 버그를 수정함
- DiffUtil item 비교 수정
- areItemsTheSame에서 아이템의 고유 넘버를 비교하고
- areContentsTheSame에서 아이템 전체 정보를 비교해서 정렬을 하는데 이를 제대로 이용하지 않음
- 이에 대한 코드를 수정함

feat: Recent 기능(클릭 시 디테일 이동 및 장바구니 아이콘) 구현 및 수정

---

app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/UpdateCartUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartUseCase.kt
app/src/main/java/com/woowa/banchan/ui/common/event/SingleEvent.kt
app/src/main/java/com/woowa/banchan/ui/detail/CartUpdateFragment.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/fragment_cart_update.xml
app/src/main/res/values/strings.xml

- close #78 
- Detail 화면에서 장바구니, 유저 아이콘 클릭시 화면 이동
- 중복 아이템 삽입 처리
- 일부 클릭 이벤트 ViewModel로 이전 ( #83 View에서 직접 클릭이벤트를 처리하지 않도록 모두 ViewModel로 이전해야 해서 우선은 지금 구현하는 기능이라도 전과 다르게 ViewModel에 클릭 이벤트를 위임하였습니다.
- 이미 있는 아이템의 경우 어떻게 처리하면 좋을까 고민하였습니다.
- 이미 있는 경우 삽입이 안 되게 하면 그만이긴 하지만, 사용자의 편의를 위해 수정할 수 있으면 좋을 것 같다고 생각했습니다.
그래서 이미 존재할 경우
위와 같이 수정할 수 있는 다이얼로그를 띄어주었습니다!

feat: Detail 기능 추가

---

app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeRVTag.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/HomeRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/viewholder/SoupSideHeaderViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeRecyclerViewViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/main/adapter/viewholder/MainHeaderViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
app/src/main/res/layout/item_home.xml
app/src/main/res/layout/item_main_linear.xml

- close #74 
- 아이템이 갱신될 때 스크롤이 최상단으로 올라가지 않게 한다.
- 정렬 상태가 유지되도록 한다.
- 페이로드를 활용하여 체크표시만 전환되게 한다.
- header와 subheader가 갱신 안 되게 하는 방법은 없을까?
-  SealedClass로 임의의 id를 지정해주어 DiffUtil이 정상작동 되도록 해결
- 기존에는 null값을 삽입해주었기 때문에 DiffUtil이 제 기능을 하지 못 하여 아이템이 전체 갱신돼서 스크롤이 위로 올라가는 거였음
- Cart의 상태가 바뀔 때 카트아이콘만 바뀌게 하기
- payload를 구현하였습니다.
- 저희의 현재 RecyclerView는 Main 탭을 예로 들면 MainRVAdapter 안에 HomeRVAdapter와 그외 헤더가 있는 구조입니다.
- 기존에는 새로운 아이템이 받아와지면 MainRVAdpater에 submitList를 하였습니다.
- MainRVAdapter의 구조는 1: Header, 2: SubHeader, 3: HomeRecyclerView 이렇게 되어있습니다.
- MainRVAdapter에 submitList를 하면 1번과 2번은 같지만, 3번은 다르게 됩니다. (상태가 바뀐 새로운 List를 제출하였기 때문)
- 그래서 페이로드든, DiffUtil이든 뭐든 상관 없이 3번은 새로 그려지게 되었고,
- 그 결과 HomeRecyclerView는 무조건 화면이 깜빡였습니다.
- 이를 해결하기 위해 MainRVAdapter에 submitList를 하는 것이 아니라, 
- HomeRVAdapter에 submitList를 …

fix: Food Item 갱신 버그 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/RecentPreviewRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentGridItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeRecyclerViewViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestItemAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestItemViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestViewHolder.kt
app/src/main/res/layout/fragment_recent.xml
app/src/main/res/layout/item_best.xml
app/src/main/res/layout/item_best_recyclerview.xml
app/src/main/res/layout/item_home.xml
app/src/main/res/layout/item_main_linear.xml
app/src/main/res/layout/item_recent.xml
app/src/main/res/layout/item_recent_grid.xml
app/src/main/res/layout/item_recyclerview.xml

- close #49 
- GridLayout에 쓰이는 Item의 간격을 match_parent로 설정.
item의 넓이를 match_parent로 한 후 spanCount만 설정해주면 GridLayout의 간격은 잘 정리가 됩니다.
하지만 match_parent인 아이템은 GridLayout에서 밖에 활용할 수 없어서
결국 유사한 item을 하나 더 만들 수 밖에 없습니다.
이 과정에서 보일러플레이트 코드가 많이 생성될 것 같아서 고민하였지만,
재활용하기 위해 억지로 코드에 로직을 추가하는 것이 오히려 더 복잡해질 것 같아서
유사한 item을 만드는 방법을 선택하였습니다.

fix: GridLayout 간격 수정

---

app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestViewHolder.kt

- close #86 
- RecyclerView에 onItemTouchListener 추가
- 가로스크롤을 신경쓰면 세로가 안 되고, 세로를 신경쓰면 가로가 안 됐습니다.
- 둘 다 잡는 방법이 무엇이 있을까 고민하고 다른 분들 레포를 염탐하던 중..
- 웅재님, 영무님 코드에서 좋은 것을 발견하여.....
- 따왔습니다... 내일 커피한잔 사드려야겠습니다 ㅋㅋㅋㅋ
``` kotlin
MotionEvent.ACTION_DOWN -> {
lastX = e.x.toInt()
lastY = e.y.toInt()
}
```
`MotionEvent.ACTION_DOWN`은 말 그대로 사용자가 화면을 눌렀을 때 발생합니다.
이때, 마지막으로 터치한 부분의 x좌표와 y좌표를 기록합니다.
``` kotlin
MotionEvent.ACTION_MOVE -> {
val distanceX = abs(lastX - e.x)
val distanceY = abs(lastY - e.y)
if (distanceY > distanceX)
rv.parent.requestDisallowInterceptTouchEvent(false)
else
rv.parent.requestDisallowInterceptTouchEvent(true)
}
```
`MotionEvent.ACTION_MOVE`는 사용자가 터치를 한 상태로 스크롤을 할 때 발생합니다.
이때, 움직인 x의 거리와 y의 거리를 계산하여 lastX, lastY의 거리와의 차이를 계산합니다.
그리고 만약 X축으로 움직인 거리가 더 많다면 …

fix: Horizontal Scroll 중첩 문제 해결

---

app/src/main/java/com/woowa/banchan/domain/model/Cart.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CheckHeaderViewHolder.kt

- close #102 
- 화면의 전체 선택 또는 선택 해제 클릭 시 화면 전체가 깜빡이는 버그를 수정
- 전체 선택 및 선택 해제가 적절히 동작하지 않는 버그 수정
- 카트의 최상단 헤더 전체 선택 및 선택 해제의 뷰를 보여주기 위한 조건
- 기존에는 비트 연산으로 카트가 담기는지 안담기는지를 판단했고, 이를 헤더에 전달해 전체 선택을 보여줄 지 선택 해제를 보여줄 지를 결정했다.
- 하지만 이 비트 연산은 연산이 복잡하고 자칫 잘못했을 경우 오버플로우가 발생하게 되어 적합하지 않다고 고려되었다.
- 따라서, 카트의 총 개수와 체크가 되어있는 개수를 비교해 보여주는 것으로 결정했다.

fix: 카트 화면 깜박임 및 전체 선택 주문 오류 버그 수정

---

app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt

- close #117 
- 프래그먼트 초기화 시 메인스레드에서 하는 작업이 과부하 되는 것이 원인
- 이를 viewpager2의 offscreenPagerLimit을 설정해주어 preload한다.

refactor: 로딩 시 화면 끊김 대응

---

app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/DeleteCartUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/UpdateCartUseCaseImpl.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/DeleteCartUseCase.kt
app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartUseCase.kt
app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
app/src/main/java/com/woowa/banchan/ui/common/recyclerview/RVItem.kt
app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
app/src/main/java/com/woowa/banchan/ui/home/HomeRVTag.kt
app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/OrderDetailRVAdapter.kt
app/src/main/res/layout/activity_order_detail.xml
app/src/main/res/values/strings.xml

- close #130 
한번에 많은 이슈를 해결하게 돼서 죄송합니다....
- update와 delete가 리스트가 리스트로 처리될 수 있도록 vararg로 변경
- delete는 즉각 처리, update는 일괄 처리 되도록 변경
- 체크된 것만 캐시가 되는 것이 아닌 현재 화면에 보이는 모든 카트를 ViewModel에 저장해 두었다가 화면에서 벗어날 때 업데이트 되도록 변경
주호님이랑 하루종일 상의했습니다.............

feat: CartFragment 로직 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt

- close #133 
- 장바구니 화면에서 recent view로 넘어갈 때 cartCache를 업데이트한다.
- 업데이트를 하고 캐시를 비워주어야 하지만 이를 수행하지 않음
- 이로인해 생긴 버그를 고침

fix: recent에서 카트 추가할 때 장바구니 화면이 변화되지 않는 버그 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt

- Recently Viewed Products 화면에서 뒤로가기 눌렀을 때 제목이 안바뀌는 버그 수정

fix: Cart 화면 제목 버그 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt

- close #146 
- 화면 수량 입력 시 max 값 도달되면 커서가 앞으로 이동함
- 맥스값에 도달하면, 커서를 마지막으로 위치하게 함
- . 입력 시 앱 크래시
- .이 들어간 string을 toInt를 통해 변환하는 것 때문에 발생한 버그
- 이를 변경함

fix: cart 화면 수량 버그 수정

---

app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt
app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt

- close #149 
- Recent -> Detail -> Cart 이동 시 Cart 화면이 아닌 기존 Recent 화면이 보여지는 버그를 해결
- Cart Activity를 우린 SingleTask로 구현했다.    
- 그래서 두 개 이상의 같은 화면이 발생하지 않도록 막았다.
- 하지만 다시 호출할 때 기존 태스크를 그대로 불러온다는 단점이 있었다.
- Recent 뷰를 보여주고 있는 태스크를 그대로 불러와 생긴 버그이다.
- 그래서 이전 태스크를 지우고 새로 만들까를 고민했으나 공식문서를 한번 읽어보았다.
```
"singleTask"
The system creates the activity at the root of a new task or locates the activity on an existing task with the same affinity. If an instance of the activity already exists and is at the root of the task, the system routes the intent to existing instance through a call to its [onNewIntent()](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)) method, rather than creating a new instance. Meanwhile all of the other activities on top of it …
```

fix: Recent -> Detail -> Cart 이동 스택 관리

---

app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt

- close #156 
- 24시간이 지났을 때 최근 목록이 지워져야 하지만 MainThread에서 동작 돼서 앱이 죽어버림 이 버그를 수정

fix: Recent가 MainThread에서 지워지던 버그 수정
